export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const ADD_OWNER = 'ADD_OWNER';
export const REMOVE_OWNER = 'REMOVE_OWNER';
export const EDIT_OWNER = 'EDIT_OWNER';
export const CHANGE_CURRENT_OWNER_INFO = 'CHANGE_CURRENT_OWNER_INFO';
